import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_KR, Pacifico } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

const pretendard = localFont({
  src: "../../public/font/Pretendard-1.3.9/public/variable/PretendardVariable.ttf",
  variable: "--font-pretendard",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif_KR({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerif.variable} ${pretendard.variable} ${pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
